services:

  redis-db:
    image: redis:latest
    restart: always

  backend:
    build: .
    depends_on:
      - redis-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["java", "-jar", "app.jar"]
